config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true,
              uniqueness: { case_sensitive: false },
              length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
              uniqueness: { case_sensitive: false },
              format: { with: VALID_EMAIL_REGEX }
    has_secure_password     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    
    
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "Você deve estar logado para realizar esta ação"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "A publicação foi criada com sucesso"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Artigo atualizado com sucesso"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @article.destroy
        flash[:danger] = "Artigo deletado com sucesso"
        redirect_to articles_path
    end

    private
        def set_article
            @article = Article.find(params[:id])
        end

        def article_params
            params.require(:article).permit(:title, :description)
        end

        def require_same_user
            if current_user != @article.user and !current_user.admin?
                flash[:danger] = "Você só pode editar ou deletar suas próprias publicações"
                redirect_to root_path
            end
        end
        
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Login realizado com sucesso"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Há algo errado com estas informações de login"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "Você foi desconectado"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Bem vindo #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Sua conta foi atualizada com sucesso"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "O usuário e todas suas publicações foram deletadas"
        redirect_to users_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "Você só pode editar sua própria conta"
            redirect_to root_path
        end
    end

    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Apenas administradores podem realizar esta ação"
            redirect_to root_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                <div class="article-body">
                    <%= truncate(article.description, length: 100) %>
                    <div class="article-meta-details">
                        <small>Criado por: <%= article.user.username if article.user%>,
                                <%= time_ago_in_words(article.created_at) %> atrás,
                                ultima modificação: <%= time_ago_in_words(article.updated_at) %> atrás</small>
                    </div>            
                </div>
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                    <div class="article-actions">
                        <%= link_to "Editar este artigo", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                        <%= link_to "Deletar este artigo", article_path(article), method: :delete, 
                                                        data: { confirm: "Tem certeza que quer apagar este artigo?"}, 
                                                        class: "btn btn-xs btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :título %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Título do artigo", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">          
                    <%= f.label :descrição %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Corpo do artigo" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit :Publicar, class: 'btn btn-primary btn-lg' %>
                </div>
            </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancelar publicação e voltar para a lista de artigos", articles_path %> ]
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Editar arquivo existente</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Lista de todos os artigos</h1>
<div align="center">
    <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Criar artigo</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Título: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
        <ul class="listing">
            <div class="row center">
                <div class="col-md-4 col-md-offset-4">
                    <li>Criado por:</li>
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                    <li class="article-title">
                        <%= link_to @article.user.username, user_path(@article.user) %>
                    </li>
                    <li><small>
                        <%= pluralize(@article.user.articles.count, "artigo") if @article.user.articles %>
                    </small></li>
                </div>
            </div>
        </ul>
    <% end %>
    <h4 class="center description"><strong>Descrição:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>
    <div class="article-actions">
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
            <%= link_to "Editar este artigo", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Deletar este artigo", article_path(@article), method: :delete, 
                                          data: { confirm: "Tem certeza que quer apagar este artigo?"}, 
                                          class: "btn btn-xs btn-danger" %>
        <% end %>                                            
        <%= link_to "Ver todos os artigos", articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="https://www.ianealvaroproducoes.com">Arregaçando tudo</a>
            by <a href="http://www.embuscadoms.com">UnB</a>
        </small>
        <nav>
            <ul>
                <li>Não temos uma pagina About</li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "QTC", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Publicações", articles_path%></li>
        <li><%= link_to "Usuários", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ações <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Nova publicação", new_article_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Sair', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Seu Perfil <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar perfil", edit_user_path(current_user) %></li>
              <li><%= link_to "Ver perfil", user_path(current_user) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Entrar', login_path %></li>
          <li><%= link_to 'Inscreva-se', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1> Sensacionalista UnB</h1>
    <%= link_to "Inscreva-se", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "erro") %>
                        proibiu que este artigo fosse salvo:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>     
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :usuário %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :username, class: "form-control", placeholder: "Insira o nome de usuário", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">          
                    <%= f.label :email %>
                </div>
                <div class="col-sm-8">
                    <%= f.email_field :email, class: "form-control", placeholder: "Insira o email" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">          
                    <%= f.label :senha %>
                </div>
                <div class="col-sm-8">
                    <%= f.password_field :password, class: "form-control", placeholder: "Insira a senha" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit(@user.new_record? ? "Criar" : "Editar conta", class: 'btn btn-primary btn-lg') %>
                </div>
            </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancelar requisição e voltar para a lista de artigos", articles_path %> ]
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edite sua conta</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Todos os bloggerinhos</h1>
<div align="center">
    <%= will_paginate %>
    <% @users.each do |user| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4">
                    <li><%= link_to gravatar_for(user), user_path(user) %></li>
                    <li class="article-title">
                        <%= link_to user.username, user_path(user) %>
                    </li>
                    <li><small><%= pluralize(user.articles.count, "artigo") if user.articles %></small></li>
                    <% if logged_in? and current_user.admin? %>
                        <li><%= link_to "Deletar este usuário", user_path(user), method: :delete,
                              data: { confirm: "Tem certeza que quer deletar este usuário e todas suas publicações?" } %></li>
                    <% end %>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Junte-se a nós</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Bem-vindo a página de <%= @user.username %></h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
        <%= gravatar_for @user, size: 150 %>
    </div>
</div>
<h4 align="center">Artigos de <%= @user.username %></h4>
<div class="center">
    <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
    <%= will_paginate @user_articles %>
</div>